### PR TITLE
Modified template using Google, Material Design CDN

### PR DESCRIPTION
**Pull request by BalSharma**
Add more template issue #1 is complete. Have a look.

### CODE REVIEW

**Comment by rajpra808** [comment]
You did great but you changed the full template. You created a new template. What you can do is, change in a given current template and make it more beautiful or adding new features(like uploading files). Your changes have many conflicts with the current template. So I can not merge it.
The purpose of this template is to share previous year university papers or sharing other study materials, not only research papers. 
You can use material CSS to make it more beautiful.
Thanks

**Comment by BalSharma** [comment]
Not a problem at all. Please let know where you want add file uploading
features. What page? or is it ok at navigation bar? Thanks

**Comment by rajpra808** [comment]
The problem with the current template is, when we want to add a new paper in dbms.html, os.html or network.html, we have to edit the HTML file. If you create a feature, in which there is an extra card with only +  sign after current cards, and when a user clicks on this plus card, A popup should come out which asks details like title, description, author and an option to upload a file. I am not expecting to do some backend work, Just create a UI for the same.  check sample UI images here.
[Temp.pdf](https://github.com/Rajpra786/ResearchPapers-Template/files/3746443/Temp.pdf)
Thanks for showing interest in this project.

**Comment by BalSharma** [comment]
I am unhooking myself from this project.

**Pull request closed without merging**
